language: java
jdk:
- oraclejdk8
install:
- ./mvnw clean install -DskipTests=true
script: /bin/true
after_success:
  - git config --global user.email "revo"
  - git config --global user.name "01120266849ASHra"
  - cd target/
  - git init
  - git add *
  - git ls-files
  - git commit -m "commit"
  - git remote add origin https://revo:01120266849ASHra@revo-web.scm.azurewebsites.net:443/revo-web.git
  - git push origin master --force