language: java
jdk:
- oraclejdk8
install:
- ./mvnw clean install -DskipTests=true
script: /bin/true
after_success:
  - ls -la
  - git status
  -git add *
  -git push https://revo:01120266849ASHra@revo-web.scm.azurewebsites.net:443/revo-web.git